### PR TITLE
Asyncio and various fixes

### PR DESCRIPTION
**Pull request by rlippmann**
Ok, this seems to work so far...

### CODE REVIEW

**Comment by rlippmann** [comment]
Might have problems with the merge.  Are there no pre-commit hooks?

**Comment by rlippmann** [comment]
I think this needs more debugging before it can actually be released, though.  It seems to update ok for a while, then stops.

**Comment by rsnodgrass** [comment]
Go ahead and merge!!
  
  
  
  
  
  
  

  
  
>

**Comment by rlippmann** [comment]
Does that release it, or does something else need to be done?

-- Rob

On May 10, 2023, at 1:22 PM, Ryan ***@***.***> wrote:

﻿



Go ahead and merge!!










>

**Comment by rsnodgrass** [comment]
I need to release it to PyPi after the merge is done and version is bumped
in setup.py.

**Comment by rlippmann** [comment]
I haven’t entirely figured out why it has stopped updating, though.

**Pull request merged**
